package ru.stqa.pft.javawebtesting.tests;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class DeleteGroupTest extends TestBase{

  @Test
  public void deleteGroup() {
    app.goToGroupPage();
    app.selectGroup();
    app.deleteSelectedGroup();
    app.returnToGroupPage();
  }
}
